name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git identify
        run: |
          git config --global user.email "test@test.com"
          git config --global user.name "GitHub Action"

      - name: Version update
        run: npm version ${{ github.event.inputs.version }}

      - name: Push version update
        run: |
          git push origin master --follow-tags

      - name: Get tag name
        run: | 
          echo ${{github.ref_name}}

      - name: Create release
        uses: softprops/action-gh-release@v1